name: ci

on:
  push:
    branches:
      - "main"
      - "development"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./app/api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest

      - name: Update Docker Hub Repository Description
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/clockbox"
          DESCRIPTION="Devops Trabajo 14"

          curl -X PATCH "https://hub.docker.com/v2/repositories/${IMAGE_NAME}/" \
            -H "Authorization: JWT ${{ secrets.DOCKERHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"full_description": "'"$DESCRIPTION"'"}'
        if: success()
